image:
  repository: tamil17/k8s-devops-project
  tag: 4ce272e
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8085
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false