image:
  repository: tamil17/k8s-devops-project
  tag: df987ce
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8085
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false